"""Tests for OpenRouter report API endpoints and fallback generation."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


@pytest.fixture()
def openrouter_paths(tmp_path, monkeypatch):
    """Isolate OpenRouter report output under tmp_path."""
    activity = tmp_path / "artifacts" / "reports"
    activity.mkdir(parents=True, exist_ok=True)

    eval_dir = tmp_path / "data" / "processed"
    eval_dir.mkdir(parents=True, exist_ok=True)
    eval_path = eval_dir / "eval_metrics.json"
    eval_path.write_text(
        json.dumps(
            {
                "accuracy": 0.91,
                "f1_score": 0.88,
                "gate_passed": True,
                "thresholds": {"min_f1_score": 0.75, "min_accuracy": 0.8},
            }
        ),
        encoding="utf-8",
    )

    drift_path = activity / "drift_summary.json"
    drift_path.write_text(
        json.dumps(
            {
                "drift_detected": False,
                "drift_score": 0.0,
                "summary": "No drift detected",
                "drifted_columns": [],
            }
        ),
        encoding="utf-8",
    )

    hash_path = tmp_path / "data" / "raw"
    hash_path.mkdir(parents=True, exist_ok=True)
    (hash_path / "dataset_hash.txt").write_text("abc123hash", encoding="utf-8")

    monkeypatch.setattr(
        "src.api.openrouter_service.get_activity_report_dir",
        lambda: activity,
    )
    monkeypatch.setattr(
        "src.api.drift_service.get_activity_report_dir",
        lambda: activity,
    )
    monkeypatch.setattr(
        "src.api.local_dashboard.get_activity_report_dir",
        lambda: activity,
    )
    monkeypatch.setattr(
        "src.api.openrouter_service.get_project_root",
        lambda: tmp_path,
    )

    return activity


@pytest.fixture()
def openrouter_client(openrouter_paths, trained_model_path, monkeypatch):
    from src.api.config import ApiSettings
    from src.api.main import create_app

    monkeypatch.delenv("OPENROUTER_API_KEY", raising=False)
    app = create_app(settings=ApiSettings(model_path=trained_model_path))
    with TestClient(app) as client:
        yield client


@pytest.fixture()
def trained_model_path(tmp_path):
    from scripts.generate_sample_data import generate_monitoring_data
    from src.features.build_features import prepare_training_data
    from src.models.train import train_model
    from src.utils.config import load_model_config
    import joblib

    df = generate_monitoring_data(n_samples=200, random_state=42)
    config = load_model_config()
    X_train, _, y_train, _ = prepare_training_data(df, random_state=42)
    model = train_model(X_train, y_train, config)
    model_path = tmp_path / "outage_model.joblib"
    joblib.dump(model, model_path)
    return model_path


def test_get_openrouter_missing_helpful_message(openrouter_client):
    response = openrouter_client.get("/reports/openrouter")
    assert response.status_code == 200
    data = response.json()
    assert data["exists"] is False
    assert "POST /reports/openrouter/run" in data["message"]


def test_openrouter_run_without_api_key(openrouter_client, openrouter_paths):
    response = openrouter_client.post("/reports/openrouter/run")
    assert response.status_code == 200
    data = response.json()
    assert data["success"] is True
    assert data["source"] == "local_fallback"
    assert data["openrouter_api_used"] is False


def test_openrouter_report_file_created(openrouter_client, openrouter_paths):
    openrouter_client.post("/reports/openrouter/run")
    report_path = openrouter_paths / "openrouter_eval_summary.md"
    assert report_path.exists()
    content = report_path.read_text(encoding="utf-8")
    assert "OpenRouter API key was not configured" in content
    assert "Accuracy" in content or "accuracy" in content.lower()


def test_get_openrouter_returns_content(openrouter_client, openrouter_paths):
    openrouter_client.post("/reports/openrouter/run")
    response = openrouter_client.get("/reports/openrouter")
    assert response.status_code == 200
    data = response.json()
    assert data["exists"] is True
    assert data["content"]
    assert data["generated_at"]
    assert data["source"] == "local_fallback"
    assert data["preview"]


def test_no_api_key_leaked(openrouter_client, openrouter_paths, monkeypatch):
    secret = "super-secret-openrouter-key-xyz"
    monkeypatch.setenv("OPENROUTER_API_KEY", secret)

    def fake_call(*_args, **_kwargs):
        return "## LLM Summary\n\nGenerated by OpenRouter."

    monkeypatch.setattr("src.api.openrouter_service.call_openrouter", fake_call)

    response = openrouter_client.post("/reports/openrouter/run")
    assert response.status_code == 200
    body = json.dumps(response.json())
    assert secret not in body

    report_path = openrouter_paths / "openrouter_eval_summary.md"
    meta_path = openrouter_paths / "openrouter_eval_summary.meta.json"
    assert secret not in report_path.read_text(encoding="utf-8")
    assert secret not in meta_path.read_text(encoding="utf-8")


def test_dashboard_includes_openrouter_section(openrouter_client):
    response = openrouter_client.get("/")
    assert response.status_code == 200
    body = response.text
    assert "openrouter-summary" in body
    assert "btn-generate-openrouter" in body
    assert "btn-view-openrouter" in body
