#!/usr/bin/env python3
# Author: Member D — documentation audit tooling
# Responsibility: Code documentation standards / submission audit
# Last Reviewed: 2026-07-06

"""Scan Python files for author tags, docstrings, and comment coverage."""

from __future__ import annotations

import argparse
import ast
import re
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SCAN_DIRS = ("src", "scripts", "infra", "tests")
AUTHOR_RE = re.compile(r"^#\s*Author:\s*(.+)", re.MULTILINE)

# Map author tag text to team owner for submission file-ownership table
OWNER_FROM_AUTHOR: list[tuple[str, str]] = [
    ("Member A", "Ameer (Member A)"),
    ("Member B", "Bakhtiyar (Member B)"),
    ("Member C", "Sana (Member C)"),
    ("Member D", "Fazal (Member D)"),
    ("Team", "Team"),
    ("Presentation layer", "Sana (Member C)"),
]


def owner_from_author_tag(author_value: str) -> str:
    """Derive submission owner name from file author tag."""
    for prefix, owner in OWNER_FROM_AUTHOR:
        if prefix.lower() in author_value.lower():
            return owner
    if author_value and "TODO" not in author_value:
        return author_value
    return "Team"


@dataclass
class FileAudit:
    path: str
    has_author: bool
    author_value: str
    has_module_docstring: bool
    functions: int
    functions_with_docstring: int
    classes: int
    classes_with_docstring: int
    total_lines: int
    comment_lines: int

    @property
    def comment_density_pct(self) -> float:
        if self.total_lines == 0:
            return 0.0
        return round(100.0 * self.comment_lines / self.total_lines, 1)

    @property
    def func_docstring_pct(self) -> float:
        if self.functions == 0:
            return 100.0
        return round(100.0 * self.functions_with_docstring / self.functions, 1)

    @property
    def class_docstring_pct(self) -> float:
        if self.classes == 0:
            return 100.0
        return round(100.0 * self.classes_with_docstring / self.classes, 1)


def iter_py_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for name in SCAN_DIRS:
        base = root / name
        if base.is_dir():
            files.extend(sorted(base.rglob("*.py")))
    return files


def count_comment_lines(text: str) -> int:
    count = 0
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or stripped.startswith('"""') or stripped.startswith("'''"):
            count += 1
    return count


def audit_file(path: Path) -> FileAudit:
    text = path.read_text(encoding="utf-8")
    rel = path.relative_to(PROJECT_ROOT).as_posix()

    author_match = AUTHOR_RE.search(text)
    has_author = author_match is not None
    author_value = author_match.group(1).strip() if author_match else ""

    try:
        tree = ast.parse(text)
    except SyntaxError:
        return FileAudit(
            path=rel,
            has_author=has_author,
            author_value=author_value,
            has_module_docstring=False,
            functions=0,
            functions_with_docstring=0,
            classes=0,
            classes_with_docstring=0,
            total_lines=len(text.splitlines()),
            comment_lines=count_comment_lines(text),
        )

    module_doc = ast.get_docstring(tree) is not None
    fn_total = fn_doc = 0
    cls_total = cls_doc = 0

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            fn_total += 1
            if ast.get_docstring(node):
                fn_doc += 1
        elif isinstance(node, ast.ClassDef):
            cls_total += 1
            if ast.get_docstring(node):
                cls_doc += 1

    return FileAudit(
        path=rel,
        has_author=has_author,
        author_value=author_value,
        has_module_docstring=module_doc,
        functions=fn_total,
        functions_with_docstring=fn_doc,
        classes=cls_total,
        classes_with_docstring=cls_doc,
        total_lines=len(text.splitlines()),
        comment_lines=count_comment_lines(text),
    )


def write_audit_report(audits: list[FileAudit], out_path: Path) -> None:
    lines = [
        "# Python Documentation Audit Report",
        "",
        "Generated by `py scripts/audit_python_docs.py`. Re-run after documentation updates.",
        "",
        f"**Files scanned:** {len(audits)}",
        "",
        "## Summary",
        "",
    ]
    with_author = sum(1 for a in audits if a.has_author)
    with_mod = sum(1 for a in audits if a.has_module_docstring)
    lines.append(f"- Author tag present: **{with_author}/{len(audits)}**")
    lines.append(f"- Module docstring present: **{with_mod}/{len(audits)}**")
    lines.append("")
    lines.append("## Per-file results")
    lines.append("")
    lines.append(
        "| File | Author | Module doc | Fn doc % | Cls doc % | Comment % |"
    )
    lines.append("|------|--------|------------|----------|-----------|-----------|")
    for a in audits:
        author = "Yes" if a.has_author else "**No**"
        mod = "Yes" if a.has_module_docstring else "No"
        lines.append(
            f"| `{a.path}` | {author} | {mod} | {a.func_docstring_pct} | "
            f"{a.class_docstring_pct} | {a.comment_density_pct} |"
        )
    lines.append("")
    lines.append("## Gaps to address")
    lines.append("")
    for a in audits:
        gaps: list[str] = []
        if not a.has_author:
            gaps.append("missing author tag")
        if not a.has_module_docstring and not a.path.endswith("__init__.py"):
            gaps.append("missing module docstring")
        if a.functions and a.func_docstring_pct < 100:
            gaps.append(f"functions docstrings {a.func_docstring_pct}%")
        if gaps:
            lines.append(f"- `{a.path}`: {', '.join(gaps)}")
    if not any(
        not a.has_author or not a.has_module_docstring for a in audits
    ):
        lines.append("- No critical gaps in author tags or module docstrings.")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_file_ownership(audits: list[FileAudit], out_path: Path) -> None:
    lines = [
        "# File Ownership — Python Modules",
        "",
        "Auto-generated table. Fill **Owner**, **Reviewer**, **Demo explained**, and **Commenting complete**.",
        "",
        "Regenerate skeleton: `py scripts/audit_python_docs.py`",
        "",
        "| File | Author tag | Owner | Reviewer | Demo explained | Commenting complete |",
        "|------|------------|-------|----------|----------------|---------------------|",
    ]
    for a in audits:
        tag = a.author_value if a.has_author else "TODO"
        owner = owner_from_author_tag(tag)
        commenting = "Yes" if a.comment_density_pct >= 15 or a.path.endswith("__init__.py") else "Review"
        lines.append(
            f"| `{a.path}` | {tag} | {owner} | Team | Rehearsal | {commenting} |"
        )
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit Python documentation standards")
    parser.add_argument(
        "--report",
        type=Path,
        default=PROJECT_ROOT / "docs" / "code-documentation" / "audit-report.md",
    )
    parser.add_argument(
        "--ownership",
        type=Path,
        default=PROJECT_ROOT / "docs" / "code-documentation" / "file-ownership.md",
    )
    args = parser.parse_args()

    audits = [audit_file(p) for p in iter_py_files(PROJECT_ROOT)]
    write_audit_report(audits, args.report)
    write_file_ownership(audits, args.ownership)
    print(f"Wrote {args.report.relative_to(PROJECT_ROOT)}")
    print(f"Wrote {args.ownership.relative_to(PROJECT_ROOT)}")
    print(f"Scanned {len(audits)} Python files")
    missing = [a.path for a in audits if not a.has_author]
    if missing:
        print(f"Missing author tag: {len(missing)} file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
