# Member D — Windows Azure environment setup (PowerShell)
# Run from project root: .\scripts\setup_azure_env.ps1

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot
# Azure CLI writes warnings to stderr; do not treat them as terminating errors.
$AzErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = "Continue"

$SubscriptionId = if ($env:AZURE_SUBSCRIPTION_ID) { $env:AZURE_SUBSCRIPTION_ID } else { "4c3c4430-0ce6-48bc-8e33-1947f3876ebd" }
$ResourceGroup = if ($env:AZURE_RESOURCE_GROUP) { $env:AZURE_RESOURCE_GROUP } else { "rg-website-outage-mlops" }
$Location = if ($env:AZURE_LOCATION) { $env:AZURE_LOCATION } else { "centralus" }
$AcrName = if ($env:ACR_NAME) { $env:ACR_NAME } else { "acrwoutagemlops" }
$AksName = if ($env:AKS_CLUSTER_NAME) { $env:AKS_CLUSTER_NAME } else { "aks-outage-predictor" }
$StorageAccount = if ($env:AZURE_STORAGE_ACCOUNT) { $env:AZURE_STORAGE_ACCOUNT } else { "stwoutagemlops" }
$WorkspaceName = if ($env:AZURE_WORKSPACE_NAME) { $env:AZURE_WORKSPACE_NAME } else { "mlw-website-outage" }
$AppInsightsName = if ($env:APP_INSIGHTS_NAME) { $env:APP_INSIGHTS_NAME } else { "outage-predictor-insights" }

Write-Host "=== Azure setup for Website Outage MLOps ===" -ForegroundColor Cyan
az account set --subscription $SubscriptionId

$rgExists = az group exists --name $ResourceGroup
if ($rgExists -eq "false") {
    az group create --name $ResourceGroup --location $Location | Out-Null
}

$acrExists = az acr show --name $AcrName --resource-group $ResourceGroup 2>$null
if (-not $acrExists) {
    Write-Host "Creating ACR: $AcrName"
    az acr create --name $AcrName --resource-group $ResourceGroup --sku Basic --location $Location | Out-Null
}
az acr update --name $AcrName --admin-enabled true 2>$null | Out-Null

$aiExists = az monitor app-insights component show --app $AppInsightsName --resource-group $ResourceGroup 2>$null
if (-not $aiExists) {
    Write-Host "Creating Application Insights: $AppInsightsName"
    az monitor app-insights component create --app $AppInsightsName --location $Location --resource-group $ResourceGroup --application-type web | Out-Null
}

$wsExists = az ml workspace show --name $WorkspaceName --resource-group $ResourceGroup 2>$null
if (-not $wsExists) {
    Write-Host "Creating Azure ML workspace: $WorkspaceName"
    az ml workspace create --name $WorkspaceName --resource-group $ResourceGroup --location $Location | Out-Null
}

$AppInsightsConn = az monitor app-insights component show --app $AppInsightsName --resource-group $ResourceGroup --query connectionString -o tsv
$StorageConn = az storage account show-connection-string --name $StorageAccount --resource-group $ResourceGroup --query connectionString -o tsv 2>$null
$MlflowUri = az ml workspace show --name $WorkspaceName --resource-group $ResourceGroup --query mlflow_tracking_uri -o tsv

$envContent = @"
# Auto-generated by scripts/setup_azure_env.ps1 — DO NOT COMMIT
AZURE_SUBSCRIPTION_ID=$SubscriptionId
AZURE_RESOURCE_GROUP=$ResourceGroup
AZURE_LOCATION=$Location
AZURE_WORKSPACE_NAME=$WorkspaceName
AZURE_STORAGE_CONNECTION_STRING=$StorageConn
ACR_NAME=$AcrName
AKS_CLUSTER_NAME=$AksName
AKS_NAMESPACE=outage-predictor
IMAGE_NAME=outage-predictor
IMAGE_TAG=v1.0.0
APPLICATIONINSIGHTS_CONNECTION_STRING=$AppInsightsConn
APP_INSIGHTS_NAME=$AppInsightsName
MLFLOW_TRACKING_URI=$MlflowUri
ALERT_ACTION_GROUP_NAME=outage-predictor-alerts
"@

$yamlContent = @"
subscription_id: "$SubscriptionId"
resource_group: $ResourceGroup
workspace_name: $WorkspaceName
storage_account: $StorageAccount
blob_container: datasets
model_registry_name: website-outage-model
mlflow_experiment_name: website-outage-prediction
configured_for_registration: true
source: local_file
"@

Set-Content -Path (Join-Path $ProjectRoot ".env") -Value $envContent -Encoding UTF8
New-Item -ItemType Directory -Force -Path (Join-Path $ProjectRoot "configs") | Out-Null
Set-Content -Path (Join-Path $ProjectRoot "configs\azure_config.yaml") -Value $yamlContent -Encoding UTF8

Write-Host ""
$ErrorActionPreference = $AzErrorActionPreference

Write-Host "Wrote .env and configs/azure_config.yaml" -ForegroundColor Green
Write-Host "MLflow tracking URI: $MlflowUri"
Write-Host ""
Write-Host "Next: py scripts/run_azure_phase2.ps1"
