#!/usr/bin/env bash
# Member D — auto-configure local Azure environment for this project
# Run: source scripts/setup_azure_env.sh   (from project root)

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

SUBSCRIPTION_ID="${AZURE_SUBSCRIPTION_ID:-4c3c4430-0ce6-48bc-8e33-1947f3876ebd}"
RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-rg-website-outage-mlops}"
LOCATION="${AZURE_LOCATION:-centralus}"
ACR_NAME="${ACR_NAME:-acrwoutagemlops}"
AKS_NAME="${AKS_CLUSTER_NAME:-aks-outage-predictor}"
AKS_NAMESPACE="${AKS_NAMESPACE:-outage-predictor}"
STORAGE_ACCOUNT="${AZURE_STORAGE_ACCOUNT:-stwoutagemlops}"
WORKSPACE_NAME="${AZURE_WORKSPACE_NAME:-mlw-website-outage}"
APP_INSIGHTS_NAME="${APP_INSIGHTS_NAME:-outage-predictor-insights}"
IMAGE_TAG="${IMAGE_TAG:-v1}"
AKS_NODE_VM_SIZE="${AKS_NODE_VM_SIZE:-standard_b2s_v2}"

echo "=== Azure setup for Website Outage MLOps ==="
echo "Subscription: $SUBSCRIPTION_ID"
echo "Resource group: $RESOURCE_GROUP"

az account set --subscription "$SUBSCRIPTION_ID"

# Ensure resource group exists
az group show --name "$RESOURCE_GROUP" >/dev/null 2>&1 || \
  az group create --name "$RESOURCE_GROUP" --location "$LOCATION" >/dev/null

# ACR
if ! az acr show --name "$ACR_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  echo "Creating ACR: $ACR_NAME"
  az acr create --name "$ACR_NAME" --resource-group "$RESOURCE_GROUP" --sku Basic --location "$LOCATION" >/dev/null
fi

# Enable ACR admin so ACI staging can pull the image
az acr update --name "$ACR_NAME" --admin-enabled true >/dev/null 2>&1 || true
ACR_USERNAME="$(az acr credential show --name "$ACR_NAME" --query username -o tsv 2>/dev/null || true)"
ACR_PASSWORD="$(az acr credential show --name "$ACR_NAME" --query "passwords[0].value" -o tsv 2>/dev/null || true)"

# App Insights
if ! az monitor app-insights component show --app "$APP_INSIGHTS_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  echo "Creating Application Insights: $APP_INSIGHTS_NAME"
  az monitor app-insights component create \
    --app "$APP_INSIGHTS_NAME" \
    --location "$LOCATION" \
    --resource-group "$RESOURCE_GROUP" \
    --application-type web >/dev/null
fi

APP_INSIGHTS_CONN="$(az monitor app-insights component show \
  --app "$APP_INSIGHTS_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --query connectionString -o tsv)"

STORAGE_CONN="$(az storage account show-connection-string \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --query connectionString -o tsv)"

# Write local .env (gitignored)
cat > .env <<EOF
# Auto-generated by scripts/setup_azure_env.sh — DO NOT COMMIT
AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID
AZURE_RESOURCE_GROUP=$RESOURCE_GROUP
AZURE_LOCATION=$LOCATION
AZURE_WORKSPACE_NAME=$WORKSPACE_NAME
AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CONN
ACR_NAME=$ACR_NAME
ACR_USERNAME=$ACR_USERNAME
ACR_PASSWORD=$ACR_PASSWORD
AKS_CLUSTER_NAME=$AKS_NAME
AKS_NAMESPACE=$AKS_NAMESPACE
IMAGE_NAME=outage-predictor
IMAGE_TAG=$IMAGE_TAG
APPLICATIONINSIGHTS_CONNECTION_STRING=$APP_INSIGHTS_CONN
APP_INSIGHTS_NAME=$APP_INSIGHTS_NAME
ALERT_ACTION_GROUP_NAME=outage-predictor-alerts
EOF

# Write azure_config.yaml (gitignored)
cat > configs/azure_config.yaml <<EOF
subscription_id: "$SUBSCRIPTION_ID"
resource_group: $RESOURCE_GROUP
workspace_name: $WORKSPACE_NAME
storage_account: $STORAGE_ACCOUNT
blob_container: datasets
model_registry_name: website-outage-model
mlflow_experiment_name: website-outage-prediction
configured_for_registration: false
source: local_file
EOF

# Export for current shell when sourced
export AZURE_SUBSCRIPTION_ID="$SUBSCRIPTION_ID"
export AZURE_RESOURCE_GROUP="$RESOURCE_GROUP"
export AZURE_LOCATION="$LOCATION"
export AZURE_WORKSPACE_NAME="$WORKSPACE_NAME"
export AZURE_STORAGE_CONNECTION_STRING="$STORAGE_CONN"
export ACR_NAME="$ACR_NAME"
export ACR_USERNAME="$ACR_USERNAME"
export ACR_PASSWORD="$ACR_PASSWORD"
export AKS_CLUSTER_NAME="$AKS_NAME"
export AKS_NAMESPACE="$AKS_NAMESPACE"
export IMAGE_NAME="outage-predictor"
export IMAGE_TAG="$IMAGE_TAG"
export APPLICATIONINSIGHTS_CONNECTION_STRING="$APP_INSIGHTS_CONN"
export APP_INSIGHTS_NAME="$APP_INSIGHTS_NAME"

echo ""
echo "Wrote .env and configs/azure_config.yaml"
echo "ACR: ${ACR_NAME}.azurecr.io"
echo "App Insights: $APP_INSIGHTS_NAME"
echo ""
echo "Test connection:"
echo "  az account show"
echo "  az group show --name $RESOURCE_GROUP"
echo ""
echo "Next (after AKS exists):"
echo "  python3 scripts/generate_sample_data.py"
echo "  python3 scripts/train_model.py"
echo "  python3 scripts/evaluate_model.py"
echo "  python3 scripts/build_image.py --acr $ACR_NAME --tag $IMAGE_TAG --push"
echo "  python3 infra/deploy_aci.py --wait-health"
echo "  python3 infra/deploy_aks.py --wait-health"
echo ""
echo "Create AKS (if not exists):"
echo "  az aks create --resource-group $RESOURCE_GROUP --name $AKS_NAME --location $LOCATION \\"
echo "    --node-count 1 --node-vm-size $AKS_NODE_VM_SIZE --enable-addons monitoring \\"
echo "    --attach-acr $ACR_NAME --generate-ssh-keys"
